# Generated by Django 5.0 on 2023-12-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_watching',
            field=models.ManyToManyField(to='auctions.listing'),
        ),
    ]
