# Generated by Django 5.0 on 2023-12-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_user_is_watching'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_watching',
            new_name='watchlist',
        ),
    ]
