# Generated by Django 5.0 on 2023-12-31 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_is_watching_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_bid', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
