# Generated by Django 5.0 on 2023-12-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_bid_listing_bid_bid_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
    ]
