# Generated by Django 5.0 on 2024-01-03 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_is_open_user_winlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='winlist',
        ),
        migrations.AddField(
            model_name='listing',
            name='winning_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
