# Generated by Django 5.0 on 2024-01-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_comment_belongs_to_listing_comment_belongs_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
